[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "tne20002-scenario-calculator"
version = "0.0.1"
authors = [
  { name="Jason But", email="jbut@swin.edu.au" },
]
description = "TNE20002 Scenario Calculator for students and library package"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
dependencies = ["streamlit"]

[project.urls]
Homepage = "https://github.com/jason-but/tne20002-scenario-calculator"
Issues = "https://github.com/jason-but/tne20002-scenario-calculator/issues"
